schema_version = "1.0.0"
id = "sco_buttobjects"
name = "SCO ButtObjects"
version = "2.0.1"
tagline = "Easily align Objects in your scene by Active Object or 3D Cursor"
maintainer = "BEAST_of_BURDEN"
type = "add-on"
website = "https://your-support-website.com"

category = "Object"

# Blender version support
blender_version_min = "4.2.0"
blender_version_max = "5.1.0"

# License information
license = [
  "SPDX:GPL-3.0-or-later",
]

# Tags (optional, but useful)
tags = ["Object"]

